import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Clon de Twitter",
  description: "Generated by midudev's tutorial",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark max-w-[600px] w-full mx-auto">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
